# Generated by Django 4.1 on 2023-03-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='SEX',
            field=models.CharField(blank=True, help_text='Enter your prefered sex', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, help_text='Enter your hometown', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, help_text='Enter your interest', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smoke',
            field=models.CharField(blank=True, help_text='How often u smoke', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.CharField(blank=True, help_text='Enter your workplace', max_length=120, null=True),
        ),
    ]
